pipeline {
    agent any 
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Execute Script') {
            steps {
                sh 'python3 python-apps/pi_calculation.py'
                sh 'echo Script Executed Succesfully.'
            }
        }
    }
}