pipeline {
    agent {
        docker {
            image 'python:3.11.7'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'python --version'
            }
        }
    }
}