pipeline {
	agent any
	stages {
		stage('Checkout') {
			steps {
				checkout scm
			}
		}

		stage('Build') {
			steps {
				sh'''
				ls -l
				javac java-app/HelloWorld.java
				'''
			}
		}
		
		stage('Run') {
			steps {
				sh'''
				echo 'Running the Java class.'
				java HelloWorld
				'''
			}
		}
	}
}